#
# This workflow will build/test/lint the Javascript SDK
#

name: JS Build/Test/Lint

on:
  workflow_call:
  push:
    branches: ['**']
    paths: ['js/**']
  pull_request:
    branches: ['**']
    paths: ['js/**']

permissions: read-all

jobs:
  build-test-lint:
    name: Build/Test/Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    defaults:
      run:
        shell: bash
        working-directory: js/
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit
